services:
  db:
    build: ./db
    ports: ["5432:5432"]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U postgres"], interval: 5s, timeout: 3s, retries: 10 }

  vote:
    build: ./vote
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/vote
    ports: ["8080:8080"]
    depends_on: [db]

  worker:
    build: ./worker
    ports: ["8081:8080"]
    depends_on: [db]

  result:
    build: ./result
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/vote
    ports: ["8082:3000"]
    depends_on: [db]